delete dbo.BNKTXN;
delete dbo.BNKCUST;
delete dbo.BNKATYPE;
delete dbo.BNKACC;
delete dbo.TTEXT;

INSERT INTO dbo.BNKCUST VALUES
(
    'B0001',
    'FRED BLOGGS MFIUSER      ',
    '                         ',
    '123456789',
    '722 PARKLAND AVE         ',
    'MISSISSAUGA              ',
    'ON',
    'CANADA',
    'L5H3G8',
    '800-555-1234',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0002',
    'LORETTA MODERN           ',
    '                         ',
    '198463794',
    '23 SILVER SPRINGS MEWS NW',
    'CALGARY                  ',
    'AB',
    'CANADA',
    'T3B3R3',
    '800-555-3854',
    '                              ',
    'Y',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0003',
    'ELEANOR RIGBY            ',
    '                         ',
    '493768396',
    '5 FOLCROFT AVE           ',
    'TORONTO                  ',
    'ON',
    'CANADA',
    'M1N1K7',
    '800-555-3857',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0004',
    'DESMOND JONES            ',
    '                         ',
    '329471287',
    '675 OTTER CRES           ',
    'PRINCE GEORGE            ',
    'BC',
    'CANADA',
    'V2M5G8',
    '800-555-1029',
    '                              ',
    'Y',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0005',
    'FELICITY ARKWRIGHT       ',
    '                         ',
    '918746356',
    '910 DES PINS RU          ',
    'MASCOUCHE                ',
    'QC',
    'CANADA',
    'J7L1J3',
    '800-555-8275',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0006',
    'JAMES TIBERIUS KIRK      ',
    '                         ',
    '111222333',
    '12057 PIERRE BLANCHET AV ',
    'MONTREAL                 ',
    'QC',
    'CANADA',
    'H1E3P3',
    '800-555-1701',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0007',
    'MARK THYME               ',
    '                         ',
    '837567892',
    '21 CARSON AVE            ',
    'ST. JOHN"S               ',
    'NF',
    'CANADA',
    'A1E1R9',
    '800-555-4434',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0008',
    'TIMOTHY HAYE             ',
    '                         ',
    '910587636',
    '300 WILLOW ST            ',
    'NEWCASTLE                ',
    'NB',
    'CANADA',
    'E1V2Z9',
    '800-555-9910',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0009',
    'HERR BARBER              ',
    '                         ',
    '987654321',
    '5900 ATLANTIC ST         ',
    'HALIFAX                  ',
    'NS',
    'CANADA',
    'B3H1H2',
    '800-555-8745',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0010',
    'BARBARA ALLEN            ',
    '                         ',
    '758643565',
    '62 HAZLEWOOD CRES        ',
    'BRANDON                  ',
    'MB',
    'CANADA',
    'R7A2J9',
    '800-555-9637',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0011',
    'BEN DOONE                ',
    '                         ',
    '843298706',
    '140 LIVINGSTONE ST       ',
    'YORKTON                  ',
    'SK',
    'CANADA',
    'S3N3A8',
    '800-555-9543',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0012',
    'MOLLY MALONE             ',
    '                         ',
    '987456875',
    '730 NIGHTINGALE CRES     ',
    'SUMMERSIDE               ',
    'PE',
    'CANADA',
    'C1N4S8',
    '800-555-1625',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0013',
    'MARY Q. CONTRARY         ',
    '                         ',
    '764638765',
    '224 KIRKLAND PLACE       ',
    'ROXBORO                  ',
    'QC',
    'CANADA',
    'H9J2C7',
    '800-555-3474',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0014',
    'LUCY LOCKET              ',
    '                         ',
    '999888777',
    '657 OAK ST               ',
    'COLLINGWOOD              ',
    'ON',
    'CANADA',
    'L9Y2Z7',
    '800-555-9988',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0015',
    'KITTY FISHER             ',
    '                         ',
    '778657766',
    '401 CORONATION AVE       ',
    'DUNCAN                   ',
    'BC',
    'CANADA',
    'V9L2T4',
    '888-555-7745',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0016',
    'SIMON TEMPLAR            ',
    '                         ',
    '792846734',
    '796 PINEGROVE CRES       ',
    'PEMBROKE                 ',
    'ON',
    'CANADA',
    'K8A7E5',
    '888-555-0192',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0017',
    'BEN CASEY                ',
    '                         ',
    '992887655',
    '25 MIDDLE CAMP CRES      ',
    'YELLOWKNIFE              ',
    'NT',
    'CANADA',
    'X1A3C3',
    '888-555-9946',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0018',
    'QUENTIN JERGENS          ',
    '                         ',
    '886775663',
    '8 PINSENT DR             ',
    'GRAND FALLS              ',
    'NF',
    'CANADA',
    '2A22R6',
    '888-555-3366',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0019',
    'CHESTER FIELD            ',
    '                         ',
    '118877645',
    '242 OLIVER AVE           ',
    'SELKIRK                  ',
    'MB',
    'CANADA',
    'R1A1H5',
    '888-555-7456',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0020',
    'MICHELLE MABELLE         ',
    '                         ',
    '775564355',
    '190 QUEEN ST S           ',
    'RENFREW                  ',
    'ON',
    'CANADA',
    'K7V2B2',
    '888-555-1653',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0021',
    'CASEY JONES              ',
    '                         ',
    '774553668',
    '4 ERISKAY PLACE          ',
    'ROTHESAY                 ',
    'NB',
    'CANADA',
    'E2E3H5',
    '877-555-7734',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0022',
    'MARY JANE LUCAS          ',
    '                         ',
    '798781594',
    '125 SHAWGLEN RD SW       ',
    'CALGARY                  ',
    'AB',
    'CANADA',
    'T2Y1X6',
    '877-555-3857',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0023',
    'FLORENCE BLAND           ',
    '                         ',
    '197630586',
    '4491 SOUTH CRESCENT      ',
    'PORT ALBERNI             ',
    'BC',
    'CANADA',
    'V9Y1L8',
    '877-555-1728',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0024',
    'MICHAEL WATERHOLE        ',
    '                         ',
    '876459273',
    '21 BINSCARTH RD          ',
    'TORONTO                  ',
    'ON',
    'CANADA',
    'M4W1Y2',
    '877-555-3927',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0025',
    'ROBIN ZEGG               ',
    '                         ',
    '640298644',
    '37 ROCKWOOD ST           ',
    'OTTAWA                   ',
    'ON',
    'CANADA',
    'K1N8L8',
    '877-555-2956',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0026',
    'FRED BEAR                ',
    '                         ',
    '294856372',
    '27 HESS ST N             ',
    'HAMILTON                 ',
    'ON',
    'CANADA',
    'L8R2S5',
    '877-555-0012',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0027',
    'MAVIS HATTY              ',
    '                         ',
    '847364821',
    '17 FORT SACKVILLE RD     ',
    'BEDFORD                  ',
    'NS',
    'CANADA',
    'B4A2G6',
    '877-555-7739',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0028',
    'MALCOLM BEAMISH          ',
    '                         ',
    '384508237',
    'DES PINS RU              ',
    'BELOEIL                  ',
    'QC',
    'CANADA',
    'J3G3E9',
    '877-555-9822',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0029',
    'JOHN JACOB SCHMIDT       ',
    '                         ',
    '592759291',
    '29 GRAHAM AVE            ',
    'ST ALBERT                ',
    'AB',
    'CANADA',
    'T8N1T4',
    '877-555-9337',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0030',
    'ADAM FIRSTMAN            ',
    '                         ',
    '887464820',
    '189 SHORT ST             ',
    'SIMCOE                   ',
    'ON',
    'CANADA',
    'N3Y3E1',
    '877-555-5592',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0031',
    'JOHN SMITH               ',
    '                         ',
    '337566986',
    '52 FORREST ST            ',
    'SYDNEY MINES             ',
    'NS',
    'CANADA',
    'B1V2B5',
    '877-555-8846',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0032',
    'MARY ANN JONES           ',
    '                         ',
    '773554266',
    '1205 FIR ST              ',
    'WHITEHORSE               ',
    'YT',
    'CANADA',
    'Y1A4C3',
    '877-555-9952',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0033',
    'JAMES FRASER             ',
    '                         ',
    '448669567',
    '770 ELM RU E             ',
    'FARNHAM                  ',
    'QC',
    'CANADA',
    'J2N1E6',
    '877-555-3385',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0034',
    'GORDON MACKENZIE         ',
    '                         ',
    '559843326',
    '6775 EAGLES DR           ',
    'VANCOUVER                ',
    'BC',
    'CANADA',
    'V5E4C1',
    '877-555-7777',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0035',
    'SUSAN PATEL              ',
    '                         ',
    '005438876',
    '1302 REX ST              ',
    'SARNIA                   ',
    'ON',
    'CANADA',
    'N7V3N3',
    '877-555-5566',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKCUST VALUES
(
    'B0036',
    'JAMES COLEBURN           ',
    '                         ',
    '483948347',
    '85 SPRUCE AVE            ',
    'SHAWINIGAN               ',
    'QC',
    'CANADA',
    'G9N1P9',
    '877-555-8327',
    '                              ',
    'N',
    'N',
    '                                                                              '
);

INSERT INTO dbo.BNKATYPE VALUES
(
    '1',
    'Savings        ',
    '                                                                                    '
);

INSERT INTO dbo.BNKATYPE VALUES
(
    '2',
    'Checking       ',
    '                                                                                    '
);

INSERT INTO dbo.BNKATYPE VALUES
(
    '3',
    'Investment     ',
    '                                                                                    '
);

INSERT INTO dbo.BNKATYPE VALUES
(
    '4',
    'Retirement     ',
    '                                                                                    '
);

INSERT INTO dbo.BNKATYPE VALUES
(
    '5',
    'Mortgage       ',
    '                                                                                    '
);
INSERT INTO dbo.BNKACC VALUES
(
    'B0001',
    '737590226',
    '2',
    -54.80,
    '2000-10-20',
    -514.80,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0001',
    '541374829',
    '3',
    3.60,
    '2000-10-20',
    3.61,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0001',
    '450061494',
    '1',
    290.12,
    '2000-10-20',
    750.12,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0002',
    '962732474',
    '1',
    67.68,
    '2000-10-20',
    67.69,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0003',
    '731813282',
    '2',
    432.96,
    '2000-10-20',
    432.96,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0003',
    '280458951',
    '5',
    372.24,
    '2000-10-20',
    372.24,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0004',
    '310781989',
    '3',
    795.52,
    '2000-10-20',
    795.53,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0004',
    '014289253',
    '2',
    -79.40,
    '2000-10-20',
    -79.41,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0004',
    '338886041',
    '1',
    91.14,
    '2000-10-20',
    91.14,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0004',
    '067606426',
    '4',
    192.24,
    '2000-10-20',
    192.24,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0004',
    '067606427',
    '5',
    1453.97,
    '2000-10-20',
    1453974.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0005',
    '394333383',
    '1',
    45.24,
    '2000-10-20',
    45.24,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0006',
    '612943325',
    '2',
    558.62,
    '2000-10-20',
    558.62,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0006',
    '417984029',
    '1',
    122.64,
    '2000-10-20',
    122.64,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0007',
    '684793285',
    '2',
    121.25,
    '2000-10-20',
    121.25,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0007',
    '704177665',
    '1',
    532.40,
    '2000-10-20',
    532.40,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0007',
    '931008548',
    '3',
    115.20,
    '2000-10-20',
    115.20,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0007',
    '988052896',
    '4',
    185.00,
    '2000-10-20',
    185.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0007',
    '725886910',
    '5',
    39.60,
    '2000-10-20',
    39.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0008',
    '504706312',
    '5',
    415.35,
    '2000-10-20',
    415.35,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0008',
    '698300146',
    '2',
    160.65,
    '2000-10-20',
    160.65,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0008',
    '917953926',
    '1',
    174.41,
    '2000-10-20',
    174.41,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0008',
    '126195094',
    '3',
    423.60,
    '2000-10-20',
    423.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0009',
    '613638770',
    '3',
    51.87,
    '2000-10-20',
    51.87,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0009',
    '669078553',
    '2',
    726.84,
    '2000-10-20',
    726.84,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0009',
    '492952258',
    '5',
    69.86,
    '2000-10-20',
    69.86,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0009',
    '315929853',
    '1',
    126.16,
    '2000-10-20',
    126.16,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0010',
    '740365828',
    '3',
    545.01,
    '2000-10-20',
    545.01,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0010',
    '403280080',
    '1',
    491.64,
    '2000-10-20',
    491.64,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0011',
    '836284456',
    '2',
    1092.63,
    '2000-10-20',
    1092.63,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0011',
    '097510533',
    '4',
    292.50,
    '2000-10-20',
    292.50,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0012',
    '889140501',
    '5',
    190.30,
    '2000-10-20',
    190.30,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0013',
    '833282554',
    '4',
    28.06,
    '2000-10-20',
    28.06,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0014',
    '482013421',
    '1',
    19.25,
    '2000-10-20',
    19.25,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0015',
    '440261495',
    '4',
    127.50,
    '2000-10-20',
    127.50,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0015',
    '334909021',
    '3',
    115.92,
    '2000-10-20',
    115.92,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0015',
    '021501544',
    '1',
    222.60,
    '2000-10-20',
    222.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0016',
    '250299477',
    '3',
    148.50,
    '2000-10-20',
    148.50,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0016',
    '742159458',
    '4',
    52.60,
    '2000-10-20',
    52.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0016',
    '516444498',
    '2',
    757.38,
    '2000-10-20',
    757.38,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0017',
    '824144721',
    '5',
    49.40,
    '2000-10-20',
    49.40,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0017',
    '734967143',
    '3',
    373.20,
    '2000-10-20',
    373.20,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0017',
    '509231712',
    '1',
    317.40,
    '2000-10-20',
    317.40,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0017',
    '632352126',
    '2',
    609.74,
    '2000-10-20',
    609.74,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0018',
    '535696493',
    '2',
    436.01,
    '2000-10-20',
    436.01,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0018',
    '310165991',
    '1',
    497.76,
    '2000-10-20',
    497.76,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0018',
    '273895979',
    '4',
    158.20,
    '2000-10-20',
    158.20,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0018',
    '672164551',
    '3',
    497.17,
    '2000-10-20',
    497.17,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0019',
    '159914519',
    '2',
    336.87,
    '2000-10-20',
    336.87,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0019',
    '452206167',
    '3',
    248.16,
    '2000-10-20',
    248.16,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0019',
    '691529946',
    '5',
    50.38,
    '2000-10-20',
    50.38,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0019',
    '048424439',
    '4',
    526.05,
    '2000-10-20',
    526.05,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0020',
    '458826510',
    '2',
    111.15,
    '2000-10-20',
    111.15,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0020',
    '911829818',
    '5',
    0.00,
    '2000-10-20',
    0.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0020',
    '532404349',
    '1',
    15.34,
    '2000-10-20',
    15.34,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0021',
    '580996260',
    '4',
    433.16,
    '2000-10-20',
    433.16,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0021',
    '287569396',
    '1',
    246.01,
    '2000-10-20',
    246.01,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0021',
    '148367063',
    '3',
    397.94,
    '2000-10-20',
    397.94,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0022',
    '728190635',
    '5',
    152.49,
    '2000-10-20',
    152.49,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0023',
    '178238731',
    '1',
    432.39,
    '2000-10-20',
    432.39,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0023',
    '412718856',
    '3',
    474.00,
    '2000-10-20',
    474.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0023',
    '915945638',
    '5',
    223.44,
    '2000-10-20',
    223.44,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0023',
    '614487822',
    '2',
    318.82,
    '2000-10-20',
    318.82,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0024',
    '575140550',
    '3',
    255.78,
    '2000-10-20',
    255.78,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0024',
    '876614916',
    '4',
    58.90,
    '2000-10-20',
    58.90,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0024',
    '485960434',
    '2',
    176.12,
    '2000-10-20',
    176.12,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0024',
    '766484266',
    '1',
    419.75,
    '2000-10-20',
    419.75,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0025',
    '323914645',
    '2',
    66.57,
    '2000-10-20',
    66.57,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0025',
    '255909083',
    '4',
    1.68,
    '2000-10-20',
    1.68,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0025',
    '472365347',
    '3',
    390.57,
    '2000-10-20',
    390.57,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0025',
    '289919943',
    '1',
    277.30,
    '2000-10-20',
    277.30,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0026',
    '507537831',
    '5',
    120.80,
    '2000-10-20',
    120.80,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0026',
    '103842702',
    '2',
    2.98,
    '2000-10-20',
    2.98,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0026',
    '025399550',
    '4',
    351.00,
    '2000-10-20',
    351.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0027',
    '938696955',
    '3',
    215.73,
    '2000-10-20',
    215.73,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0028',
    '459775790',
    '5',
    92.95,
    '2000-10-20',
    92.95,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0028',
    '494077239',
    '3',
    0.00,
    '2000-10-20',
    0.00,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0028',
    '090543026',
    '4',
    682.08,
    '2000-10-20',
    682.08,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0028',
    '930886725',
    '1',
    72.54,
    '2000-10-20',
    72.54,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0028',
    '916885997',
    '2',
    942.33,
    '2000-10-20',
    942.33,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0029',
    '143898379',
    '4',
    697.60,
    '2000-10-20',
    697.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0029',
    '374126010',
    '3',
    809.55,
    '2000-10-20',
    809.55,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0029',
    '946046572',
    '1',
    185.85,
    '2000-10-20',
    185.85,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0029',
    '420152459',
    '2',
    196.70,
    '2000-10-20',
    196.70,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0029',
    '213882639',
    '5',
    121.41,
    '2000-10-20',
    121.41,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0030',
    '766814914',
    '5',
    216.36,
    '2000-10-20',
    216.36,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0030',
    '821196059',
    '3',
    75.99,
    '2000-10-20',
    75.99,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0031',
    '302433706',
    '3',
    134.20,
    '2000-10-20',
    134.20,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0032',
    '624576817',
    '4',
    322.05,
    '2000-10-20',
    322.05,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0033',
    '620669186',
    '5',
    30.60,
    '2000-10-20',
    30.60,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0033',
    '722655363',
    '2',
    91.20,
    '2000-10-20',
    91.20,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0033',
    '658801552',
    '1',
    41.70,
    '2000-10-20',
    41.70,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0034',
    '228552724',
    '4',
    79.92,
    '2000-10-20',
    79.92,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0034',
    '154460444',
    '2',
    271.44,
    '2000-10-20',
    271.44,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0034',
    '582910260',
    '5',
    592.02,
    '2000-10-20',
    592.02,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0035',
    '990768568',
    '3',
    52.06,
    '2000-10-20',
    52.06,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0035',
    '446453890',
    '1',
    216.64,
    '2000-10-20',
    216.64,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0035',
    '054228132',
    '4',
    252.56,
    '2000-10-20',
    252.56,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0035',
    '564387410',
    '2',
    222.64,
    '2000-10-20',
    222.64,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0035',
    '389624103',
    '5',
    858.78,
    '2000-10-20',
    858.78,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0036',
    '443556119',
    '2',
    430.05,
    '2000-10-20',
    430.05,
    '                                                                 '
);

INSERT INTO dbo.BNKACC VALUES
(
    'B0036',
    '388063602',
    '5',
    399.33,
    '2000-10-20',
    399.33,
    '                                                                 '
);
INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '541374829',
    '1999-12-25-01.01.01.000001',
    '                          ',
    1.00,
    'Christmas present 1                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '541374829',
    '1999-12-25-01.01.02.000002',
    '                          ',
    2.00,
    'Christmas present 2                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '541374829',
    '1999-12-25-01.01.03.000003',
    '                          ',
    3.00,
    'Christmas present 3                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '541374829',
    '1999-12-25-01.01.04.000004',
    '                          ',
    4.00,
    'Christmas present 4                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '541374829',
    '1999-12-25-01.01.05.000005',
    '                          ',
    5.00,
    'Christmas present 5                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.01.000006',
    '                          ',
    1.00,
    'Christmas present 1                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.02.000007',
    '                          ',
    2.00,
    'Christmas present 2                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.03.000008',
    '                          ',
    3.00,
    'Christmas present 3                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.04.000009',
    '                          ',
    4.00,
    'Christmas present 4                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.05.000010',
    '                          ',
    5.00,
    'Christmas present 5                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.06.000011',
    '                          ',
    6.00,
    'Christmas present 6                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.07.000012',
    '                          ',
    7.00,
    'Christmas present 7                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.08.000013',
    '                          ',
    8.00,
    'Christmas present 8                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.09.000014',
    '                          ',
    9.00,
    'Christmas present 9                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '1',
    '1',
    '962732474',
    '1999-12-25-02.03.10.000015',
    '                          ',
    10.00,
    'Christmas present 10                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.01.000016',
    '                          ',
    1.00,
    'Christmas present 1                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.02.000017',
    '                          ',
    2.00,
    'Christmas present 2                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.03.000018',
    '                          ',
    3.00,
    'Christmas present 3                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.04.000019',
    '                          ',
    4.00,
    'Christmas present 4                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.05.000020',
    '                          ',
    5.00,
    'Christmas present 5                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.06.000021',
    '                          ',
    6.00,
    'Christmas present 6                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.07.000022',
    '                          ',
    7.00,
    'Christmas present 7                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.08.000023',
    '                          ',
    8.00,
    'Christmas present 8                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.09.000024',
    '                          ',
    9.00,
    'Christmas present 9                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.10.000025',
    '                          ',
    10.00,
    'Christmas present 10                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.11.000026',
    '                          ',
    11.00,
    'Christmas present 11                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.12.000027',
    '                          ',
    12.00,
    'Christmas present 12                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.13.000028',
    '                          ',
    13.00,
    'Christmas present 13                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.14.000029',
    '                          ',
    14.00,
    'Christmas present 14                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.15.000030',
    '                          ',
    15.00,
    'Christmas present 15                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.16.000031',
    '                          ',
    16.00,
    'Christmas present 16                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.17.000032',
    '                          ',
    17.00,
    'Christmas present 17                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.18.000033',
    '                          ',
    18.00,
    'Christmas present 18                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.19.000034',
    '                          ',
    19.00,
    'Christmas present 19                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.20.000035',
    '                          ',
    20.00,
    'Christmas present 20                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.21.000036',
    '                          ',
    1.00,
    'Christmas present 21                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.22.000037',
    '                          ',
    2.00,
    'Christmas present 22                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.23.000038',
    '                          ',
    3.00,
    'Christmas present 23                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.24.000039',
    '                          ',
    4.00,
    'Christmas present 24                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.25.000040',
    '                          ',
    5.00,
    'Christmas present 25                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.26.000041',
    '                          ',
    6.00,
    'Christmas present 26                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.27.000042',
    '                          ',
    7.00,
    'Christmas present 27                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.28.000043',
    '                          ',
    8.00,
    'Christmas present 28                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.29.000044',
    '                          ',
    9.00,
    'Christmas present 29                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.30.000045',
    '                          ',
    10.00,
    'Christmas present 30                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.31.000046',
    '                          ',
    11.00,
    'Christmas present 31                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.32.000047',
    '                          ',
    12.00,
    'Christmas present 32                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.33.000048',
    '                          ',
    13.00,
    'Christmas present 33                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.34.000049',
    '                          ',
    14.00,
    'Christmas present 34                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.35.000050',
    '                          ',
    15.00,
    'Christmas present 35                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.36.000051',
    '                          ',
    16.00,
    'Christmas present 36                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.37.000052',
    '                          ',
    17.00,
    'Christmas present 37                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.38.000053',
    '                          ',
    18.00,
    'Christmas present 38                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.39.000054',
    '                          ',
    19.00,
    'Christmas present 39                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.40.000055',
    '                          ',
    20.00,
    'Christmas present 40                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.41.000056',
    '                          ',
    1.00,
    'Christmas present 41                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.42.000057',
    '                          ',
    2.00,
    'Christmas present 42                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.43.000058',
    '                          ',
    3.00,
    'Christmas present 43                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.44.000059',
    '                          ',
    4.00,
    'Christmas present 44                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '310781989',
    '1999-12-25-04.04.45.000050',
    '                          ',
    5.00,
    'Christmas present 45                                                                                                                                  ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '067606426',
    '1999-12-21-01.01.01.000051',
    '                          ',
    101.00,
    'Christmas present 1                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '067606426',
    '1999-12-22-01.01.02.000052',
    '                          ',
    102.00,
    'Christmas present 2                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '067606426',
    '1999-12-23-01.01.03.000053',
    '                          ',
    103.00,
    'Christmas present 3                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '067606426',
    '1999-12-24-01.01.04.000054',
    '                          ',
    104.00,
    'Christmas present 4                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '1',
    '1',
    '067606426',
    '1999-12-25-01.01.05.000055',
    '                          ',
    105.00,
    'Christmas present 5                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0004',
    '2',
    ' ',
    null,
    '2004-06-18-10.04.07.774550',
    '                          ',
    0.00,
    '675 OTTER CRES           PRINCE GEORGE            BCCANADAV2M5G8800-555-1029                              NN                                          ',
    '675 OTTER CRES           PRINCE GEORGE            BCCANADAV2M5G8800-555-1029                              YN                                          ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0002',
    '2',
    ' ',
    null,
    '2004-07-26-12.11.19.607040',
    '                          ',
    0.00,
    '22 SILVER SPRINGS MEWS NWCALGARY                  ABCANADAT3B3R3800-555-3854                              NN                                          ',
    '23 SILVER SPRINGS MEWS NWCALGARY                  ABCANADAT3B3R3800-555-3854                              YN                                          ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '450061494',
    '2004-07-26-17.12.15.628900',
    '                          ',
    -10.00,
    'Transferred to a/c 737590226                                                                                                                          ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '2',
    '737590226',
    '2004-07-26-17.12.15.628901',
    '                          ',
    10.00,
    'Transferred from a/c 450061494                                                                                                                        ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '2',
    ' ',
    null,
    '2004-07-26-17.12.31.717880',
    '                          ',
    0.00,
    '722 PARKLAND AVE         MISSISSAUGA              ONCANADAL5H3G8800-555-1234                              NN                                          ',
    '723 PARKLAND AVE         MISSISSAUGA              ONCANADAL5H3G8800-555-1234                              NN                                          ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '450061494',
    '2004-07-27-09.35.12.644070',
    '                          ',
    -200.00,
    'Transferred to a/c 737590226                                                                                                                          ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '2',
    '737590226',
    '2004-07-27-09.35.12.644071',
    '                          ',
    200.00,
    'Transferred from a/c 450061494                                                                                                                        ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '2',
    ' ',
    null,
    '2004-08-02-11.06.11.846330',
    '                          ',
    0.00,
    '723 PARKLAND AVE         MISSISSAUGA              ONCANADAL5H3G8800-555-1234                              NN                                          ',
    '722 PARKLAND AVE         MISSISSAUGA              ONCANADAL5H3G8800-555-1234                              NN                                          ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '1',
    '450061494',
    '2004-09-07-04.45.12.366580',
    '                          ',
    -250.00,
    'Transferred to a/c 737590226                                                                                                                          ',
    '                                                                                                                                                      ',
    '                           '
);

INSERT INTO dbo.BNKTXN VALUES
(
    'B0001',
    '1',
    '2',
    '737590226',
    '2004-09-07-04.45.12.366581',
    '                          ',
    250.00,
    'Transferred from a/c 450061494                                                                                                                        ',
    '                                                                                                                                                      ',
    '                           '
);
INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '00',
    'Mainframe Express                                                          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '01',
    'Maintain your current systems efficiently, and deliver new systems         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '02',
    'cost-effectively with Mainframe Express. It provides an intuitive          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '03',
    'workstation-based environment that includes state-of-the-art application   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '04',
    'development tools that can dramatically increase programmer                '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '1',
    '05',
    'productivity.                                                              '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '00',
    'Mainframe Express for PL/I                                                 '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '01',
    'Mainframe Express is the obvious development and testing platform          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '02',
    'choice for e-Business-enabling mainframe-based applications. It provides   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '03',
    'a consistent, high-performance platform for the development and testing    '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '04',
    'of Internet-based, and client/server applications that assimilate          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '05',
    'mission-critical PL/I and emerging information technologies and transfer   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '2',
    '06',
    'innovative business applications across the enterprise.                    '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '00',
    'Revolve                                                                    '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '01',
    'Automate legacy application management and analysis with Revolve. It       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '02',
    'reduces the cost and complexity of projects ranging from everyday bug      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '03',
    'fixes to large-scale system refurbishment through powerful code analysis   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '04',
    'and inventory features that automatically determine and locate an          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '3',
    '05',
    'application"s source components.                                           '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '00',
    'Mainframe Emulators                                                        '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '01',
    'These powerful sub-systems provide full support for the mainframe          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '02',
    'environment from a single view on the Windows workstation. Mainframe       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '03',
    'Emulators support popular mainframe environments, including CICS,          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '04',
    'IMS, DB2 and Assembler programs, enabling complex integration testing      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '4',
    '05',
    'right on the workstation.                                                  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '00',
    'Mainframe Testing                                                          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '01',
    'Test Suite is a comprehensive testing environment that brings workstation  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '02',
    'productivity to mainframe application development. It enables your         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '03',
    'programmers to perform multiple levels of application testing at their     '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '04',
    'workstations, ensuring fast, accurate results as well as increased testing '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '5',
    '05',
    'confidence throughout your organization.                                   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '6',
    '00',
    'Remote IMS                                                                 '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '6',
    '01',
    'Remote IMS provides direct access to mainframe databases from the          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '6',
    '02',
    'workstation. Databases can be transparently read and updated directly      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '6',
    '03',
    'from any workstation, and workstations running Remote IMS can              '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '6',
    '04',
    'combine mainframe, network and local databases in a test mode.             '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '00',
    'Mainframe Connectivity                                                     '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '01',
    'Micro Focus mainframe connectivity provides COBOL                          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '02',
    'developers the best of two worlds with Mainframe Access™, SQL              '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '03',
    'Option™ for DB2, IMS Option™, and CICS Option™ - products that             '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '04',
    'exploit the best features of workgroup and enterprise architectures.       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '05',
    'Mainframe source control systems, data, and processes are now              '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '06',
    'accessible from Mainframe Express™, the industry"s leading                 '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '07',
    'development environment. Flexible and intuitive graphic presentations for  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '08',
    'debugging and analyzing code are the complement to the traditional         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDA20A',
    '7',
    '09',
    'strengths of mainframe operations.                                         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '00',
    'Net Express                                                                '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '01',
    'Extend your enterprise to the Internet and client/server platforms with    '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '02',
    'Net Express, an integrated development environment that protects your      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '03',
    'legacy investments and increases programmer productivity. Net Express      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '04',
    'dramaticaly recuces time-to-solution by allowing you to reuse existing     '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '05',
    'business logic and data and easily extend it to new platforms such as      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '1',
    '06',
    'UNIX, Windows and the Internet.                                            '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '00',
    'Server Express™                                                            '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '01',
    'Building Next Generation e-Business Applications. Micro Focus              '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '02',
    'Server Express is the platform of choice for deploying e-Business          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '03',
    'and distributed applications. Server Express accelerates enterprise        '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '04',
    'COBOL application performance to the next level providing the fastest      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '2',
    '05',
    'ever Micro Focus COBOL© product for UNIX.                                  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '00',
    'Object COBOL Developer Suite for UNIX                                      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '01',
    'Develop and deploy client/server and standalone COBOL applications         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '02',
    'on all leading UNIX platforms with this integrated development             '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '03',
    'environment. The Developer Suite generates high performing, scalable       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '04',
    'and portable business applications that can take advantage of popular      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '3',
    '05',
    'databases and server resources including the Internet.                     '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '4',
    '00',
    'Application Server                                                         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '4',
    '01',
    'Extend your applications and eliminate the need for additional             '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '4',
    '02',
    'programming with Application Server, a set of powerful run-time facilities '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '4',
    '03',
    'that enable COBOL applications to be portable across all leading UNIX      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '4',
    '04',
    'platforms.                                                                 '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '00',
    'AppMaster Builder                                                          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '01',
    'Developers can quickly build applications with AppMaster Builder,          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '02',
    'combining extensive application coverage with your data resources.         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '03',
    'AppMaster Builder generates reliable, high-performance, high-quality       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '04',
    'COBOL while managing integration between the application, clients,         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '5',
    '05',
    'servers and the standard technology to make them work together.            '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '00',
    'Distributed Computing Consulting Services                                  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '01',
    'Integrate your current systems with the best of new technologies and       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '02',
    'extend them to new platforms through our consulting services. Our          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '03',
    'expertise in complex and heterogeneous computing environments will         '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '04',
    'maximize the cost and efficiency of your custom solution for blending      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '05',
    'disparate technologies such as UNIX, Windows NT, PCs,                      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '6',
    '06',
    'Workstations, MVS and the Internet.                                        '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '7',
    '00',
    'Additional Enterprise Application Development Products                     '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '00',
    'Revolve                                                                    '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '01',
    'Automate legacy application management and analysis with Revolve. It       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '02',
    'reduces the cost and complexity of projects ranging from everyday bug      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '03',
    'fixes to large-scale system refurbishment through powerful code analysis   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '04',
    'and inventory features that automatically determine and locate an          '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '8',
    '05',
    'application"s source components.                                           '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '00',
    'AppMaster Renovator                                                        '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '01',
    'This powerful client/server solution dramatically improves the process of  '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '02',
    'maintaining existing COBOL systems, while facilitating the transition to   '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '03',
    'client/server and object orientation. It allows you to reuse existing      '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '04',
    'business logic within new client/server applications and to off-load       '
);

INSERT INTO dbo.TTEXT VALUES
(
    'PRDB20A',
    '9',
    '05',
    'maintenance of mission-critical applications to distributed platforms.     '
);


