INSERT INTO dbo.BNKTXN (BTX_PID, BTX_TYPE, BTX_SUB_TYPE, BTX_ACCNO, BTX_AMOUNT, BTX_DATA_OLD, BTX_DATA_NEW, BTX_FILLER) VALUES 
(
    'B0001',
    '1',
    '1',
    '451374829',

    2.00,
    'Christmas present 2                                                                                                                                   ',
    '                                                                                                                                                      ',
    '                           '
);

