      $set sourceformat(variable)

      *> Namespace: BankDemoWinForm.Properties

      *>> <summary>
      *>>   A strongly-typed resource class, for looking up localized strings, etc.
      *>> </summary>
      *> This class was auto-generated by the StronglyTypedResourceBuilder
      *> class via a tool like ResGen or Visual Studio.
      *> To add or remove a member, edit your .ResX file then rerun ResGen
      *> with the /str option, or rebuild your VS project.
       class-id BankDemoWinForm.Properties.Resources
           attribute System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")
           attribute System.Diagnostics.DebuggerNonUserCode()
           attribute System.Runtime.CompilerServices.CompilerGenerated()
       .

       working-storage section.
       01 resourceMan type System.Resources.ResourceManager static.
       01 resourceCulture type System.Globalization.CultureInfo static.

       property-id ResourceManager type System.Resources.ResourceManager static final internal
           attribute System.ComponentModel.EditorBrowsable(type System.ComponentModel.EditorBrowsableState::Advanced).
       local-storage section.
       01 temp type System.Resources.ResourceManager.
       getter.
           if object::ReferenceEquals(resourceMan null) then 
               set temp to new System.Resources.ResourceManager("BankDemoWinForm.Properties.Resources" type of BankDemoWinForm.Properties.Resources::Assembly)
               set resourceMan to temp
           end-if
           set property-value to resourceMan
       end property.

       property-id Culture type System.Globalization.CultureInfo static final internal
           attribute System.ComponentModel.EditorBrowsable(type System.ComponentModel.EditorBrowsableState::Advanced).
       getter.
           set property-value to resourceCulture
       setter.
           set resourceCulture to property-value
       end property.

       property-id Back type System.Drawing.Bitmap static final internal.
       local-storage section.
       01 obj object.
       getter.
           set obj to self::ResourceManager::GetObject("Back" resourceCulture)
           set property-value to obj as type System.Drawing.Bitmap
       end property.

       method-id NEW
                    attribute System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode").
       procedure division.

       end method.

       end class.
